[package]
name = "kernel-5_15"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
package-name = "kernel-5.15"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
# Use latest-kernel-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/35e2e2432267615ca5cbe519eb781747524fdbb903d8c4dd0e231d38561a21be/kernel-5.15.173-118.169.amzn2.src.rpm"
sha512 = "7f67e93f2c9232da790b24ab406988c97bf56b0967df9784d9472799c14393eba87965b5388b164314e3032d4d7c9236fd68ff7c511bd267cff791db3416febf"
force-upstream = true

[[package.metadata.build-package.external-files]]
# Use latest-neuron-srpm-url.sh to get this.
url = "https://yum.repos.neuron.amazonaws.com/aws-neuronx-dkms-2.19.64.0.noarch.rpm"
sha512 = "5c0938f513101e7b6234d5ef4c450151c913976fec89bcba5f46ce57cba5cef764f1085080f7e145516ed9b49f7c4aad4e16b7ac07fda848b654ba34448051a0"
force-upstream = true

[build-dependencies]
microcode = { path = "../microcode" }
