[package]
name = "kernel-5_10"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
package-name = "kernel-5.10"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
# Use latest-kernel-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/0882910cd8b755b83ca76915856c240798bb0c0eefa651896eb34015b6577bea/kernel-5.10.230-223.885.amzn2.src.rpm"
sha512 = "f03f0b2aafaadc592dd571829fb5a0b0c36739e92afad6c134061ebf4b68df8ed89b369f553927fb72d08a4ed35d0b7f4a72951be3df894865ecb0908378bc0b"
force-upstream = true

[[package.metadata.build-package.external-files]]
# Use latest-neuron-srpm-url.sh to get this.
url = "https://yum.repos.neuron.amazonaws.com/aws-neuronx-dkms-2.19.64.0.noarch.rpm"
sha512 = "f93aa097ea0515533817ce9737810cb8b025c35c3d4367c2e667292c0692d525ffbc9b7972fe957174e206a82e394cc7e076e5b399e1050f2c5f6ed129d4d739"
force-upstream = true

[build-dependencies]
microcode = { path = "../microcode" }
