[package]
name = "kernel-6_1"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
package-name = "kernel-6.1"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
# Use latest-kernel-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/al2023/blobstore/c5625ba4f37a38809773fa50b769735602f1e4e50d60cb7127ed6231d0695e95/kernel-6.1.119-129.201.amzn2023.src.rpm"
sha512 = "258a96b9216c187352405f856d69d0fd7edb2e9c89066ad098c9e50bbdfc0c13c666d74fe8b919fa5ffa03dc9f802bff454b03e7f455cf2d3d92a4a66c7d4987"
force-upstream = true

[[package.metadata.build-package.external-files]]
# Use latest-neuron-srpm-url.sh to get this.
url = "https://yum.repos.neuron.amazonaws.com/aws-neuronx-dkms-2.19.64.0.noarch.rpm"
sha512 = "5c0938f513101e7b6234d5ef4c450151c913976fec89bcba5f46ce57cba5cef764f1085080f7e145516ed9b49f7c4aad4e16b7ac07fda848b654ba34448051a0"
force-upstream = true

[build-dependencies]
microcode = { path = "../microcode" }
